#python3 ../test.py --data_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/txt/violin_txt/test_vi_3d_data.txt --ngf 64 --batch_size 1 --model test_full_add --name 10_param_0point005 --checkpoints_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/res --norm batch --gpu_ids 0 --eval --verbose --results_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/results

python3 ../test.py --data_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/txt/violin_txt/test_vi_3d_data.txt --ngf 64 --batch_size 1 --model test_full_add --name 10_param_0point01 --checkpoints_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/res --norm batch --gpu_ids 0 --eval --verbose --results_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/results

python3 ../test.py --data_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/txt/violin_txt/test_vi_3d_data.txt --ngf 64 --batch_size 1 --model test_full_add --name 10_param_0point03 --checkpoints_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/res --norm batch --gpu_ids 0 --eval --verbose --results_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/results

python3 ../test.py --data_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/txt/violin_txt/test_vi_3d_data.txt --ngf 64 --batch_size 1 --model test_full_add --name 10_param_0point05 --checkpoints_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/res --norm batch --gpu_ids 0 --eval --verbose --results_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/results

python3 ../test.py --data_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/txt/violin_txt/test_vi_3d_data.txt --ngf 64 --batch_size 1 --model test_full_add --name 10_param_0point07 --checkpoints_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/res --norm batch --gpu_ids 0 --eval --verbose --results_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/results

python3 ../test.py --data_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/txt/violin_txt/test_vi_3d_data.txt --ngf 64 --batch_size 1 --model test_full_add --name 10_param_0point09 --checkpoints_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/res --norm batch --gpu_ids 0 --eval --verbose --results_dir /mnt/feoh-public/sig4share/students/b4/nakanose/b4/data_URMP/Sub-URMP/car_gan/results